type = "sync"

[sync_reader]
cluster = true
address = "r-bp16uk6iq1sfxg6zbn.redis.rds.aliyuncs.com:6379"
sync_rdb = true
sync_aof = true
username = "username"
password = "D3xP!4@AS!d@6q"

[redis_writer]
cluster = true
address = "r-bp11qmfi4t0vwdbw8d.redis.rds.aliyuncs.com:6379"
username = "username"
password = "D3xP!4@AS!d@6q"

[advanced]
# pprof_port = 40000
log_level = "info"