type = "sync"

[sync_reader]
cluster = false
address = "10.0.128.155:6379"
sync_rdb = true
sync_aof = true
username = "username"
password = "D3xP!4@AS!d@6q"

[redis_writer]
cluster = false
address = "10.0.128.138:6379"
username = "username"
password = "D3xP!4@AS!d@6q"

[advanced]
pprof_port = 40000
log_level = "info"
dir = "data-1"