type = "sync"

[sync_reader]
cluster = true
address = "127.0.0.1:33001"
sync_rdb = true
sync_aof = true

[redis_writer]
cluster = true
address = "127.0.0.1:33005"

[advanced]
pprof_port = 40000
log_level = "info"
